version: "3"
services:
  forge:
    container_name: minecraft_forge
    image: marcermarc/forge:latest
    volumes:
      - ./data:/mnt/minecraft
    environment:
      - HEAP=1G
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    stdin_open: true
    tty: true
